# Generated by Django 2.1.7 on 2019-03-03 04:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('naps', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Building',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.AlterField(
            model_name='spot',
            name='building',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='naps.Building'),
        ),
        migrations.AlterField(
            model_name='spot',
            name='noise',
            field=models.CharField(default='Average', max_length=7),
        ),
        migrations.AlterField(
            model_name='spot',
            name='notes',
            field=models.CharField(default='No notes', max_length=500),
        ),
    ]
