# Generated by Django 2.1.7 on 2019-03-03 05:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('naps', '0002_auto_20190302_2333'),
    ]

    operations = [
        migrations.CreateModel(
            name='Noise',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.CharField(default='Average', max_length=7)),
            ],
        ),
        migrations.AlterField(
            model_name='spot',
            name='noise',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='naps.Noise'),
        ),
    ]
